# Generated by Django 4.1.1 on 2022-09-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="evaluator_job_id",
            field=models.CharField(max_length=36),
        ),
    ]
