# Generated by Django 4.1.2 on 2023-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_alter_submission_evaluator_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="gitlab_branch",
            field=models.CharField(default="master", max_length=256),
        ),
    ]
