name: CI
on: [push, pull_request]
jobs:
    Lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Provision
          run: sudo ./bin/provision-system.sh
          shell: bash

        - name: Run Black
          run: black --check .
          shell: bash

        - name: Run ISort
          run: isort --check --diff .
          shell: bash

        - name: Run Pylint
          run: DJANGO_SETTINGS_MODULE=ui.settings pylint --recursive=y .
          shell: bash

        # - name: Run MyPy
        #   run: mypy .
        #   shell: bash



    Test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Provision
            run: sudo ./bin/provision-system.sh
            shell: bash

          - name: PyTest
            run: pytest
            shell: bash

    Publish:
        needs:
          - Test
          - Lint
        runs-on: ubuntu-latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Get Current Branch Name
            uses: nelonoel/branch-name@v1

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: jokeswar/vmchecker_ui:${{ env.BRANCH_NAME }}
